---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  ansible-lint .
#  yamllint .
platforms:
  - name: ubuntu_focal
    image: ubuntu:focal
    dockerfile: ../Dockerfile.j2
    # pre_build_image: true
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: sudo
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
role_name_check: 1